Added contact senors to the main wheels
yujinrobot/kobuki pull request #425
Opened 2020-10-02 11:00 UTC by ipa-kut

This will enable wheel drop sensors event publishers

2020-10-08 16:34 UTC, corot requested changes
Same as the other PR; didn't test properly

2020-10-08 16:34 UTC, corot commented on kobuki_description/urdf/kobuki_gazebo.urdf.xacro
> +        <wheel_left_sensor_name>wheel_left</wheel_left_sensor_name>
sensor name is wheel_drop; what about calling this:
`<wheel_drop_left_sensor_name>wheel_drop_left</wheel_drop_left_sensor_name>`
`<wheel_drop_right_sensor_name>wheel_drop_right</wheel_drop_right_sensor_name>`

2020-10-08 16:34 UTC, corot commented on kobuki_description/urdf/kobuki_gazebo.urdf.xacro
> +      <sensor type="contact" name="wheel_left">
wheel_drop_left,  see below

2020-10-08 16:34 UTC, corot commented on kobuki_description/urdf/kobuki_gazebo.urdf.xacro
>      </gazebo>
`</sensor>` missing

2020-10-08 16:34 UTC, corot commented on kobuki_description/urdf/kobuki_gazebo.urdf.xacro
>      </gazebo>
same

2021-05-16 11:13 UTC, corot commented
Hey @ipa-kut, I have retaken your work here, I hope you don't mind

2021-05-16 11:23 UTC, corot approved these changes

2023-09-27 18:28 UTC, stonier approved these changes

2023-10-11 04:36 UTC, merged