Improve Python 3 compatibility
yujinrobot/kobuki pull request #426
Opened 2020-10-08 19:47 UTC by galou

2020-10-09 02:43 UTC, corot requested changes
Minor issues from automated formatter

2020-10-09 02:43 UTC, corot commented on kobuki_testsuite/src/kobuki_testsuite/drift_estimation.py
> +                print(("Kobuki Testsuite: initial centre [%s]" % self._centred_gyro_angle))
Unneeded double parentheses

2020-10-09 02:43 UTC, corot commented on kobuki_testsuite/src/kobuki_testsuite/motion_travel_forward.py
> +                print(("Distance %s"%math.sqrt(current_distance_sq)))
Double parentheses unneeded

2020-10-12 08:03 UTC, galou commented on kobuki_testsuite/src/kobuki_testsuite/motion_travel_forward.py
> +                print(("Distance %s"%math.sqrt(current_distance_sq)))
Fixed!

2020-10-12 08:23 UTC, corot approved these changes

2020-10-12 08:24 UTC, corot commented
Are you using this test suite?

2020-10-12 08:25 UTC, merged

2020-10-12 12:03 UTC, galou commented
I don't use this test suite but the warning appeared when running `catkin build` and it looked that it could be fixed easily, so I just did it.